name: Build and Deploy WebSocket Server

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "websocket-server/**"
      - ".github/workflows/deploy-websocket-server.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push WebSocket Server Image
        uses: docker/build-push-action@v6
        with:
          context: ./websocket-server
          file: ./websocket-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cex-websocket-server:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cex-websocket-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy WebSocket Server to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cex-websocket-server:${{ github.sha }}

            docker rm -f cex-websocket-server || true

            docker run -d \
              --name cex-websocket-server \
              --network cex-network \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -e CONSUMER_GROUP="${{ secrets.CONSUMER_GROUP }}" \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/cex-websocket-server:${{ github.sha }}

            docker image prune -f
